<?php

declare(strict_types=1);

namespace Webfloo\Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Creates super_admin and editor roles with appropriate permissions.
 *
 * Prerequisites:
 *   php artisan shield:generate --all --panel=admin
 *
 * Usage:
 *   php artisan db:seed --class="Webfloo\Database\Seeders\ShieldRolesSeeder"
 *
 * Idempotent -- safe to run multiple times.
 */
class ShieldRolesSeeder extends Seeder
{
    /**
     * Resource models the editor role can manage.
     *
     * @var list<string>
     */
    /*
     * Newsletter subscribers contain PII (email, name, IP) in GDPR scope.
     * Only super_admin may access — do NOT add `newsletter_subscriber` here
     * without legal/privacy review. A dedicated role (e.g. `compliance_officer`)
     * with narrow permissions is the right escalation path.
     */
    private const EDITOR_RESOURCES = [
        'post',
        'post_category',
        'page',
        'project',
        'service',
        'testimonial',
        'faq',
        'menu_item',
    ];

    /**
     * Policy actions generated by shield for each resource.
     *
     * @var list<string>
     */
    private const RESOURCE_ACTIONS = [
        'view_any',
        'view',
        'create',
        'update',
        'delete',
        'restore',
        'force_delete',
        'force_delete_any',
        'restore_any',
        'replicate',
        'reorder',
    ];

    /**
     * Page permission keys the editor role can access.
     * Format: view_{class_name_snake}
     *
     * @var list<string>
     */
    private const EDITOR_PAGE_PERMISSIONS = [
        'view_home_page_settings',
        'view_contact_page_settings',
        'view_site_settings',
        'view_theme_settings',
    ];

    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $guard = 'web';

        // 1. Create roles (idempotent)
        $superAdmin = Role::firstOrCreate(
            ['name' => 'super_admin', 'guard_name' => $guard]
        );

        $editor = Role::firstOrCreate(
            ['name' => 'editor', 'guard_name' => $guard]
        );

        // 2. super_admin gets ALL permissions
        $allPermissions = Permission::where('guard_name', $guard)->pluck('name');
        $superAdmin->syncPermissions($allPermissions);

        // 3. Build editor permission set
        $editorPermissions = $this->buildEditorPermissions($guard);
        $editor->syncPermissions($editorPermissions);

        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $this->command->info("Roles seeded: super_admin ({$allPermissions->count()} permissions), editor ({$editorPermissions->count()} permissions)");
    }

    /**
     * @return \Illuminate\Support\Collection<int, string>
     */
    private function buildEditorPermissions(string $guard): \Illuminate\Support\Collection
    {
        $permissions = collect();

        // Resource permissions
        foreach (self::EDITOR_RESOURCES as $resource) {
            foreach (self::RESOURCE_ACTIONS as $action) {
                $permissions->push("{$action}_{$resource}");
            }
        }

        // Page permissions
        foreach (self::EDITOR_PAGE_PERMISSIONS as $pagePermission) {
            $permissions->push($pagePermission);
        }

        // Filter to only existing permissions (shield:generate must run first)
        $existing = Permission::where('guard_name', $guard)
            ->whereIn('name', $permissions->all())
            ->pluck('name');

        if ($existing->count() < $permissions->count()) {
            $missing = $permissions->diff($existing);
            $this->command->warn("Missing permissions (run shield:generate first): {$missing->implode(', ')}");
        }

        return $existing;
    }
}
