<?php

declare(strict_types=1);

namespace Webfloo\Http\Controllers\Frontend;

use Illuminate\Contracts\View\View;
use Webfloo\Models\Page;
use Webfloo\Models\Post;

/**
 * Draft preview behind temporary signed URLs (1h, generated by the
 * PreviewAction in the admin panel). Extends PageController to reuse
 * renderPage()/templateData() — preview must render exactly what
 * publishing will.
 */
class PreviewController extends PageController
{
    public function page(Page $page): View
    {
        return $this->renderPage($page);
    }

    public function post(Post $post): View
    {
        return view('webfloo::frontend.blog.show', ['post' => $post]);
    }
}
